baseURL: "https://kenny50.github.io/"

languageCode: "en-us"
title: "KenCiao 數位"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 10
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Tech-Blog
      title: Blog posts
      url: /posts
      weight: 1
    - identifier: read
      name: Read
      title: Read
      url: /read
      weight: 2
    - identifier: digital-nomad
      name: Digital-Nomad
      title: Digital-Nomad
      url: /digital-nomad
      weight: 3
    - identifier: Cooking
      name: Cooking
      title: Cooking
      url: /cooking
      weight: 4

params:
  title: "Ken Chang"
  description: 數位遊牧
  # staticPath: ""  # The path to serve the static files from
  favicon: "https://lh3.googleusercontent.com/a/ACg8ocJdBkMHHg9SweA2gsH6kYGNG1hjwYK7yyWHESWZUd1Pgdo=s96-c"
  animate: true

  navbar:
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: true

  hero:
    enable: true
    intro: "目前和好想工作室長期合作"
    title: "CiaoDigi 公司網站建置中"
    subtitle: "軟體服務、數位轉型"
    content: "網頁、後端、AI、APP 全方位的團隊支援，從商業需求到落地應用，為目標制定最合適的解決方案"
    image: /images/bc.png
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "網站連結"
      url: ""
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/Kenny50
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/yh-c/
      # customIcons:
      #   - icon: /fav.png
      #     url: "https://example.com"

  about:
    enable: true
    title: "About Me"
    image: "https://avatars.githubusercontent.com/u/65593417?v=4"
    content: |-
      自由接案者、軟體工程師，熟悉 Android, Kotlin, NodeJS，接案的經歷讓我更能兼顧技術和商業目標

      個性喜歡交流，舉辦過 Effective Kotlin 線上讀書會  ，線下活動和 GDG Tainan 推廣過 Jetpack compose，也在多場技術活動擔任志工以及分享者，架過線上版的 Kotlin IDE ，來解決活動中沒 Intellij 的參與者或是線上運行的  Code sample 
    skills:
      enable: true
      title: "最近用的技術棧"
      items:
        - "Kotlin"
        - "Android"
        - "JavaScript"
        - "Node"
        - "Express"
        - "Docker"
  
  contact:
    enable: true
    # title: "Custom Name"
    content: 隨時開放，無論你有問題還是只是想打聲招呼，我都會盡力回覆你！如果幾個工作日內沒收到回覆，可以再嘗試重寄
    btnName: Mail me
    btnLink: mailto:yunghancareer@gmail.com

  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: 主講Ｘ技術分享
        content: 為你的專案加點模組化
        url: https://gdg.community.dev/events/details/google-gdg-kaohsiung-presents-devfest-kaohsiung-tainan-2022/
        image: https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/DF22-Bevy-EventThumb%402x_gIPRNwd.png
      - title: 主講Ｘ技術分享
        content: Coroutine 在 Android 的應用
        url: https://gdg.community.dev/events/details/google-gdg-tainan-presents-coroutinezai-androidde-ying-yong/
        image: https://res.cloudinary.com/startup-grind/image/fetch/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/https://res.cloudinary.com/startup-grind/image/upload/c_fill%2Cdpr_2.0%2Cf_auto%2Cg_center%2Cq_auto:good/v1/gcs/platform-data-goog/event_banners/gdev-eccosystems-bevy-chapters-thumbnail_D0AYZGY.png
      - title: 協辦Ｘ台南 Google Developer Group
        content: Build with AI
        url: https://gdg.community.dev/events/details/google-gdg-tainan-presents-cong-ren-shi-dao-shi-zhan-genai-ji-chu-jie-shao-dao-lun-build-with-ai-tainan/
        image: https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/Copy%20of%20GDG24-BwAI-DevBadge-Participant_3PbEOXy.png
      - title: 協辦Ｘ台南 && 台北 Google Developer Group
        content: 用 Gemini API + RAG 打造會LINE 貼圖的聊天機器人 | Build with AI Taipei x Tainan
        url: https://gdg.community.dev/events/details/google-gdg-tainan-presents-yong-gemini-api-rag-da-zao-hui-line-tie-tu-de-liao-tian-ji-qi-ren-build-with-ai-taipei-x-tainan/
        image: https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/Copy%20of%20GDG24-BwAI-DevBadge-Participant_3PbEOXy.png
      - title: 協辦Ｘ台南 Google Developer Group
        content: 從認識到實戰 - Gemini 開發工具介紹 | Build with AI Tainan
        url: https://gdg.community.dev/events/details/google-gdg-tainan-presents-cong-ren-shi-dao-shi-zhan-gemini-kai-fa-gong-ju-jie-shao-build-with-ai-tainan/
        image: https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/Copy%20of%20GDG24-BwAI-DevBadge-Participant_3PbEOXy.png
      - title: 協辦Ｘ台南 Google Developer Group
        content: 從認識到實戰 - Prompt Engineering & GenAI 應用情境介紹 | Build with AI Tainan
        url: https://gdg.community.dev/events/details/google-gdg-tainan-presents-cong-ren-shi-dao-shi-zhan-prompt-engineering-amp-genai-ying-yong-qing-jing-jie-shao-build-with-ai-tainan/
        image: https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/Copy%20of%20GDG24-BwAI-DevBadge-Participant_3PbEOXy.png
      - title: 協辦Ｘ台南 Google Developer Group
        content: 從認識到實戰 - Gemini 結合各種 API 應用 | Build with AI Tainan
        url: https://gdg.community.dev/events/details/google-gdg-tainan-presents-cong-ren-shi-dao-shi-zhan-gemini-jie-he-ge-zhong-api-ying-yong-build-with-ai-tainan/
        image: https://res.cloudinary.com/startup-grind/image/upload/c_fill,w_500,h_500,g_center/c_fill,dpr_2.0,f_auto,g_center,q_auto:good/v1/gcs/platform-data-goog/events/Copy%20of%20GDG24-BwAI-DevBadge-Participant_3PbEOXy.png

  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: 金玉峰投顧 - 訂閱制內容平台
        content: 依照會員層級，限制可閱讀內容權限，針對月、季、年推出不同訂閱方案，並在因應法規、公司流程以及金流服務的權衡之下，為客戶找出合適解法
        image: https://prod.jinyufeng.com.tw/assets/background-d69e2ba2.png
        featured:
          name: Demo
          link: https://prod.jinyufeng.com.tw/
        badges:
          - "Node"
          - "Express"
          - "Javascript"
      - title: 鑫蘊林科 - Mobility AI
        content: 在智慧巴士上，將光學雷達硬體資料篩選、計算、壓縮，在保證即時性的同時，兼顧不斷擴大的資料量級設計解法，讓乘客可以看到路面現況同步的點雲圖效果，另一挑戰是將 Base64 圖像資料，搭配 AI 模型資料進行二次繪製，並將其轉變成串流媒體資源進行推流
        image: https://imgcdn.cna.com.tw/www/postwrite/2023/20230401/00338304.20230401426995981M.jpg
        featured:
          # name: Link
          # link: https://www.cna.com.tw/postwrite/chi/338304
          name: Youtube
          link: https://www.youtube.com/watch?v=z_b0Z2uSp6g
        badges:
          - "Node"
          - "Express"
          - "Javascript"
          - "ffmepg"
          - "WebSocket"
      - title: 台達電內部系統
        content: 以 Webview 為 UI，將原生硬體功能 ex . 藍芽、NFC、相機、錄音 包裝成 library 與 JS 互動，並協同網頁端共同實踐 PWA 以完成離線支援 
        image: https://www.taiwanled.org.tw/storage/system/member/09_deltaww_800x600.jpg
        badges:
          - "Kotlin"
          - "Android"
          - "PWA"

  footer:
    recentPosts:
      path: "read"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/Kenny50
      linkedin: https://www.linkedin.com/in/yh-c/
      # instagram: https://instagram.com