baseURL: "https://kenny50.github.io/Blog/"
languageCode: "en-us"
title: "Hugo Profile yaml"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 10
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: blog
      name: Blog
      title: Blog posts
      url: /posts
      weight: 1
    - identifier: read
      name: Read
      title: Read
      url: /read
      weight: 2
    - identifier: travel
      name: Travel
      title: Travel
      url: /Travel
      weight: 3
    - identifier: Cooking
      name: Cooking
      title: Cooking
      url: /Cooking
      weight: 4

params:
  title: "張永翰"
  description: 數位漂泊中
  # staticPath: ""  # The path to serve the static files from
  favicon: "https://lh3.googleusercontent.com/a/ACg8ocJdBkMHHg9SweA2gsH6kYGNG1hjwYK7yyWHESWZUd1Pgdo=s96-c"
  animate: true

  navbar:
    menus:
      disableAbout: true
      disableExperience: true
      disableEducation: true
      disableProjects: true
      disableAchievements: true
      disableContact: true

  about:
    enable: true
    title: "About Me"
    image: "https://lh3.googleusercontent.com/a/ACg8ocJdBkMHHg9SweA2gsH6kYGNG1hjwYK7yyWHESWZUd1Pgdo=s96-c"
    content: |-
      三年軟體工程師，熟悉 Android, Kotlin，也寫 NodeJS，發現後端的坑有夠大．

      個性喜歡交流，舉辦過 Effective Kotlin 線上讀書會  ，線下活動和 GDG Tainan 推廣過 Jetpack compose，也在多場技術活動擔任志工以及分享者，架過線上版的 Kotlin IDE ，來解決活動中沒 Intellij 的參與者或是線上運行的  Code sample 
    skills:
      enable: true
      title: "最近用的技術棧"
      items:
        - "Kotlin"
        - "Android"
        - "JavaScript"
        - "Node"
        - "Express"
        - "Docker"
  
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!
    btnName: Mail me
    btnLink: mailto:yunghancareer@gmail.com

  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: 技術分享
        content: 為你的專案加點模組化
        url: https://gdg.community.dev/events/details/google-gdg-kaohsiung-presents-devfest-kaohsiung-tainan-2022/
        # image: /images/achievment.jpg
      - title: 技術分享
        content: Coroutine 在 Android 的應用
        url: https://gdg.community.dev/events/details/google-gdg-tainan-presents-coroutinezai-androidde-ying-yong/

  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: 金玉峰投顧 - 訂閱制內容平台
        content: 依照會員層級，限制可閱讀內容權限，針對月、季、年推出不同訂閱方案，並在因應法規、公司流程以及金流服務的權衡之下，為客戶找出合適解法
        image: https://staging-jinyufeng-file-bucket.s3.ap-northeast-1.amazonaws.com/article/213e046d-f9aa-4ccd-bf65-a3933f91730a
        featured:
          name: Demo
          link: https://jinyufeng-staging.jinyufeng.com.tw/
        badges:
          - "Node"
          - "Express"
          - "Javascript"
      - title: 鑫蘊林科 - Mobility AI
        content: 在智慧巴士上，將光學雷達硬體資料篩選、計算、壓縮，在保證即時性的同時，兼顧不斷擴大的資料量級設計解法，讓乘客可以看到路面現況同步的點雲圖效果，另一挑戰是將 Base64 圖像資料，搭配 AI 模型資料進行二次繪製，並將其轉變成串流媒體資源進行推流
        image: https://imgcdn.cna.com.tw/www/postwrite/2023/20230401/00338304.20230401426995981M.jpg
        featured:
          name: Link
          link: https://www.cna.com.tw/postwrite/chi/338304
        badges:
          - "Node"
          - "Express"
          - "Javascript"
          - "ffmepg"
          - "WebSocket"
      - title: 台達電內部系統
        content: 以 Webview 為 UI，將原生硬體功能 ex . 藍芽、NFC、相機、錄音 包裝成 library 與 JS 互動，並協同網頁端共同實踐 PWA 以完成離線支援 
        image: https://www.taiwanled.org.tw/storage/system/member/09_deltaww_800x600.jpg
        badges:
          - "Kotlin"
          - "Android"
          - "PWA"

  footer:
    recentPosts:
      path: "posts"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/Kenny50
      linkedin: https://www.linkedin.com/in/yh-c/
      # instagram: https://instagram.com